### ISSUE TITLE
MAX_SOCK_NUM for W5500

### ISSUE THREAD

**Issue by sstaub** [PaulStoffregen/Ethernet#11]
The W5500 chip has max. 8 sockets. But it is defined in ethernet.h and w5100.h only with max. 4 Sockets.

**Comment by PaulStoffregen** [comment]
This is by design.  Very likely going to change the W5500 default to 4K buffers, since it makes a substantial improvement on connections with typical non-LAN network latency.  The extra sockets also consume extra RAM due to the state caching, which is a big deal on memory-limited AVR.
