### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by Rotzbua** [PaulStoffregen/Ethernet#16]
Hi,
a license file is missing and it seems that there is a mixture of different licenses in comments (gnu2.0 and mit).
Seems similar to original repository https://github.com/arduino-libraries/Ethernet/issues/41 .
Best

**Comment by PaulStoffregen** [comment]
Adding missing headers.  https://github.com/PaulStoffregen/Ethernet/commit/009c59d2cf50f886598e47db1a2407c81abf7349

That's as good as it gets.  Lots of code from different people... I've rewritten quite a lot, but I'm doing going to redo it all just so everything can be the same license.  This is as much as I'm doing.
