### ISSUE TITLE
w5500 - 8 Socket Support

### ISSUE THREAD

**Issue by brendanmatkin** [PaulStoffregen/Ethernet#21]
The W5200/5500 support up to 8 sockets (with smaller buffers) but the library only supports up to 4 (`MAX_SOCK_NUM` in a few places).

I'm plan to work on it and submit a pull request if I get something clean enough - but if it's already in the works maybe someone (or @PaulStoffregen) can chime in here! Is there a fundamental problem that limits this library to 4 sockets? 

@sstaub has it working well with https://github.com/sstaub/Ethernet3, but that library has some other issues that are giving me trouble (mostly they based it on the wiznet library which has some blocking functions).

It seems these chips dedicate a new socket to each multicast group, and I need to join 5+ for sACN universes. If someone has experience with this and knows I'm barking up the wrong tree, let me know!

**Comment by vysocan** [comment]
I'm using this library with 8 sockets. And it works. I shoud have copy of it in my gihub/libraries. I just replaced 4 with 8. But planning to make my fork to keep up with master changes. Maybe you will faster.

If I remember well Pauls option to 4 was larger buffer.

**Comment by brendanmatkin** [comment]
Thanks @vysocan! I read in the forums that it didn't work (a few years ago) - I didn't get it working but I missed what is now mentioned in issue #23.
