### ISSUE TITLE
changing MAX_SOCK_NUM value

### ISSUE THREAD

**Issue by jgastonraoul** [PaulStoffregen/Ethernet#22]
Hi !

There is a compilation problem when we try to change MAX_SOCK_NUM value in w5100.h, because it conflicts with SOCKETS definition (line 264 of MAX_SOCK_NUM).
Could we change SOCKETS = 4 to SOCKETS = MAX_SOCK_NUM or set SOCKETS with SSIZE and SMASK in w5100.cpp (that would make sense because socket count depends of socket buffer size...) ?

Regards,

Jérémie

**Comment by PaulStoffregen** [comment]
Currently the library is not designed to easily change this setting.
