### ISSUE TITLE
esp32 dev module and w5500

### ISSUE THREAD

**Issue by MaxESP** [PaulStoffregen/Ethernet#35]
dear sir,

i have an error cannot declare variable 'server' to be of abstract type 'EthernetServer'

i have change virtual void begin() = 0; for server.h

it's don't work

**Comment by uzi18** [comment]
minimal source to reproduce?

**Comment by MaxESP** [comment]
Dear Sir,

I am sorry it was a mistake from me about spi config all working very good with esp32 +w5500

what about websocket for that library do you have some idear

thanks a lot
