### ISSUE TITLE
EthernetServer not compilable on PlatformIO/ESP32

### ISSUE THREAD

**Issue by Miq1** [PaulStoffregen/Ethernet#43]
Unfortunately the EthernetServer examples are not working for Platformio. A line of 
```
EthernetServer server(23);
```
will result in the error 
```
error: cannot declare variable 'server' to be of abstract type 'EthernetServer'
 EthernetServer server(23);
                ^
In file included from src\main.cpp:10:0:
C:/Users/Micha/.platformio/lib/Ethernet_ID872/src/Ethernet.h:253:7: note:   because the following virtual functions are pure within 'EthernetServer':     
 class EthernetServer : public Server {
       ^
In file included from C:/Users/Micha/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:152:0,
                 from src\main.cpp:1:
C:/Users/Micha/.platformio/packages/framework-arduinoespressif32/cores/esp32/Server.h:28:18: note:      virtual void Server::begin(uint16_t)
     virtual void begin(uint16_t port=0) =0;
```
The common workaround seems to be to roll back to the arduino-esp32 release 1.7.0 in PlatformIO, but that is quite outdated and lacks other fixes having been applied in the meantime.
Anyone having ideas of how to solve this permanently?

**Comment by PaulStoffregen** [comment]
This is Teensy's copy of Ethernet.  This is the wrong place to report ESP32 problems.

I am no longer maintaining this library for non-Teensy platforms.
