### ISSUE TITLE
NativeEthernet AdvancedChatServer EthernetServer.accept() not working

### ISSUE THREAD

**Issue by doeringJ** [PaulStoffregen/Ethernet#44]
in this example for Teensy 4.1 the
EthernetClient newClient = server.accept(); 
never returns a newClient even the Client is connected (tested with putty)

I guess the reason is because the fnet_socket_accept(…) function is not called in the EthernetServer.accept() function as seen in the EthernetServer.available() function.

**Comment by vjmuzik** [comment]
I just pushed a fix, I tested it using that example so I can confirm that specifically works so barring any unforeseen differences with other projects using server.accept() it should now function correctly.

**Comment by doeringJ** [comment]
Tested the fix and can confirm it works. Thank you.
