### ISSUE TITLE
Support for Teensy 4.0

### ISSUE THREAD

**Issue by gannaramu** [PaulStoffregen/Ethernet#49]
Hello Paul, Just wanted to check if this library supports teensy 4.0 boards

**Comment by PaulStoffregen** [comment]
Yes, it works with all Teensy boards.

But Teensy 4.1 has native ethernet.  The forum is the place to ask questions, not github issue.

**Comment by gannaramu** [comment]
Thank you, I will make sure to post in the forum next time, Thanks for the input!
