### ISSUE TITLE
Support for LAN8720A (WT32-ETH01) Adapter possible

### ISSUE THREAD

**Issue by knopserl** [PaulStoffregen/Ethernet#56]
Hello Paul,

would it be possible (manageabl) to get support for the LAN8720A module which is used and several ESP32 board such as the WT32_ETH01)?
I have a working solution for WebServer and there are also UPD libraries available

https://github.com/urbanze/esp32-eth/blob/master/eth.h
https://www.arduinolibraries.info/libraries/async-udp_wt32_eth01

Main main purpose is to use the WT32_ETH01 with Ethernet  and PoE if possible to build an ArtNet solution. I used the ESP32 + W500 and the this standrd Ethernet library with this ArtNet library https://github.com/hideakitai/ArtNet, but it has a 20sec delay with the W5500 so I used the ESP32 with the integrated LAN8720A but the ArtNet library wants an EthernetUDP Class and that is not what I get with the libs for the LAN8720A but an Ethernet Lib (ETH) and this AsynUDP Lib.
Any possibiliy to get the LAN8720A into this Ethernet lib or how would I use the AsyncUDP with ArtNet?

Thanks a lot.

**Comment by PaulStoffregen** [comment]
Of all the places on the internet you might ask, this is absolutely the wrong one.

This repository is only for the Wiznet ethernet chips, and only for using them with Teensy.
